AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  JobManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/hello/index.handler
      Runtime: nodejs18.x
      Events:
        ApiJobManagement:
          Type: Api
          Properties:
            Path: /hello
            Method: get